### ISSUE TITLE
MacOS error

### ISSUE THREAD

**Issue by mika76** [andmatand/vector-paint#1]
I placed this into a folder, gave it a .love extension and then ran it, and got this error. Same error when I try to run via terminal and the `love .` command

```
Error

Syntax error: main.lua:287: malformed number near '0b1111111100000000'



Traceback

[C]: at 0x0102148b20
[C]: in function 'require'
[C]: in function 'xpcall'
[C]: in function 'xpcall'
```

**Comment by andmatand** [comment]
hmmm what version of LÖVE are you using?

**Comment by mika76** [comment]
11.3b it says. I'm pretty new to love (although not to lua - used corona before) so I might be missing something obvious but I have not been able to find anything about this issue anywhere...

**Comment by andmatand** [comment]
that's weird; binary literals work fine on the Linux version of LÖVE, but not the macOS one (I just tried and confirmed on a mac myself). oh well, I just changed it to use hex instead, so this is fixed now. thanks for the report!

**Comment by mika76** [comment]
Thanks for the fix - I reported it on the love project to...
